/**
 * @file transition.hpp
 * @author Albert Uchytil, Tomas Coufal
 * @brief Data structure for transition
 */
#include "transition.hpp"

/**
 * Feasibility of transition - input
 *
 * Checks the input conditions of transition. That means if in input places there
 * are enough tokens to allow the transition.
 */
bool Transition::IsFeasible() {
    std::ostringstream s;
    s << "checking feasibility for planning, transition: " << this->Id;
    debug("transition", s.str());
    std::vector<Connection*>::iterator conn_it;
    // there are enough tokens on input places
    for (conn_it = this->Inputs.begin(); conn_it != this->Inputs.end(); conn_it++) {
        s.str("");
        s << "input.cap = " << (*conn_it)->Capacity << ", tokens = " << (*conn_it)->Pl->GetCount();
        debug("transition", s.str());
        // if not enough tokens, break
        if ((*conn_it)->Pl->GetCount() < (*conn_it)->Capacity)
            return false;
    }
    debug("transition", "transition approved");
    return true;
}

/**
 * Feasibility of transition - output
 *
 * Similar function to the one above but checks the output condition for
 * transition feasibility. Checks if there is enough capacity left on output
 * places to fit all tokens generated by transition for the connection.
 */
bool Transition::IsFeasibleNow() {
    debug("transition", "checking feasibility in time");
    std::vector<Connection*>::iterator conn_it;
    // there is enough capacity on output places
    for (conn_it = this->Outputs.begin(); conn_it != this->Outputs.end(); conn_it++) {
        if (! (*conn_it)->Pl->WillFit((*conn_it)->Capacity) )
            return false;
    }
    return true;
}

/**
 * Get input place
 *
 * @return place
 */
Place* Transition::Input()
{
  if (this->Inputs.size() == 0) {
    return NULL;
  } else {
    return this->Inputs[0]->Pl;
  }
}

/**
 * Statistical function to track number of transition applications.
 *
 * @param timev Time to apply
 */
void Transition::Apply(double timev) {
  totalTime += timev;
  count++;
}

/**
 * Print statistics
 *
 * Outputs statistical table containing values: number of created and left tokens
 */
void Transition::PrintStats() {
    Stats::PrintHeader("TRANSITION " + Id, "value");
    Stats::PrintRow("Number of transitions", count);
    Stats::PrintRow("Average length", GetAverageTime());
}
